/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QldRouteImport } from './routes/qld'
import { Route as NswRouteImport } from './routes/nsw'
import { Route as ActRouteImport } from './routes/act'
import { Route as IndexRouteImport } from './routes/index'

const QldRoute = QldRouteImport.update({
  id: '/qld',
  path: '/qld',
  getParentRoute: () => rootRouteImport,
} as any)
const NswRoute = NswRouteImport.update({
  id: '/nsw',
  path: '/nsw',
  getParentRoute: () => rootRouteImport,
} as any)
const ActRoute = ActRouteImport.update({
  id: '/act',
  path: '/act',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/act': typeof ActRoute
  '/nsw': typeof NswRoute
  '/qld': typeof QldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/act': typeof ActRoute
  '/nsw': typeof NswRoute
  '/qld': typeof QldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/act': typeof ActRoute
  '/nsw': typeof NswRoute
  '/qld': typeof QldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/act' | '/nsw' | '/qld'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/act' | '/nsw' | '/qld'
  id: '__root__' | '/' | '/act' | '/nsw' | '/qld'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActRoute: typeof ActRoute
  NswRoute: typeof NswRoute
  QldRoute: typeof QldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/qld': {
      id: '/qld'
      path: '/qld'
      fullPath: '/qld'
      preLoaderRoute: typeof QldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nsw': {
      id: '/nsw'
      path: '/nsw'
      fullPath: '/nsw'
      preLoaderRoute: typeof NswRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/act': {
      id: '/act'
      path: '/act'
      fullPath: '/act'
      preLoaderRoute: typeof ActRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActRoute: ActRoute,
  NswRoute: NswRoute,
  QldRoute: QldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
